# Generated by Django 3.2.5 on 2021-07-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210711_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
