# Generated by Django 3.2.5 on 2021-07-11 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.CharField(choices=[('Car/Van', 'Car'), ('Truck', 'Truck')], default='Car/Van', max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pricing_model', models.CharField(choices=[('Per Mile', 'Mile'), ('Per Hour', 'Hour')], default='Per Mile', max_length=10)),
                ('price', models.FloatField()),
                ('max_load', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.CharField(choices=[('Car/Van', 'Car'), ('Truck', 'Truck')], default='Car/Van', max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pricing_model', models.CharField(choices=[('Per Mile', 'Mile'), ('Per Hour', 'Hour')], default='Per Mile', max_length=10)),
                ('price', models.FloatField()),
                ('max_load', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
